[package]
name = "nowoshire/namedsignal"
description = "A Signal implementation for Luau, with a nice balance of ergonomics, performance, and features."
version = "2.0.2"
license = "MIT"
authors = ["Nowoshire"]

registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://nowoshire.github.io/NamedSignal/"
repository = "https://github.com/Nowoshire/NamedSignal"

realm = "shared"
exclude = ["*"]
include = ["src/*", "LICENSE", "README.md", "wally.toml"]

[dependencies]
